# Generated by Django 3.2.15 on 2023-05-03 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_subscribe_попытка подписаться на себя'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscribe',
            name='попытка подписаться на себя',
        ),
    ]
